import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { formatDistance, formatWorkoutDate, getDateForDayOfWeek } from '../../utils/formatters';
import { Card } from '../ui/Card';
import { Button } from '../ui/Button';
import { Check, Sparkles, Target } from 'lucide-react';
export const PlanCard = ({ plan, unitSystem, isActive = false, onApplyPlan, onViewDetails, }) => {
    const runningWorkouts = plan.workouts.filter((w) => w.type !== 'rest' && w.distanceKm > 0);
    return (_jsxs(Card, { className: "p-4 bg-white border border-neutral-200/90 shadow-soft-md space-y-3.5", children: [_jsx("div", { className: "flex items-start justify-between gap-2", children: _jsxs("div", { children: [_jsxs("div", { className: "flex items-center space-x-1.5 mb-1", children: [_jsxs("span", { className: "inline-flex items-center gap-1 text-[10px] font-black uppercase tracking-wider bg-orange-50 text-[#FF5500] px-2 py-0.5 rounded-full", children: [_jsx(Sparkles, { className: "w-3 h-3" }), "AI Running Plan"] }), isActive && (_jsxs("span", { className: "inline-flex items-center gap-1 text-[10px] font-bold uppercase tracking-wider bg-emerald-50 text-emerald-600 px-2 py-0.5 rounded-full", children: [_jsx(Check, { className: "w-3 h-3" }), "Active Plan"] }))] }), _jsx("h3", { className: "text-base font-black text-neutral-900 tracking-tight", children: plan.title }), _jsxs("p", { className: "text-xs text-neutral-500 font-medium mt-0.5 flex items-center gap-1", children: [_jsx(Target, { className: "w-3.5 h-3.5 text-neutral-400" }), plan.goal] })] }) }), _jsxs("div", { className: "grid grid-cols-2 gap-2 pt-1", children: [_jsxs("div", { className: "bg-neutral-50 rounded-xl p-2.5 border border-neutral-100", children: [_jsx("span", { className: "text-[10px] font-bold uppercase tracking-wider text-neutral-400 block", children: "Schedule" }), _jsx("span", { className: "text-xs font-bold text-neutral-800 line-clamp-1 mt-0.5", children: plan.scheduleSummary })] }), _jsxs("div", { className: "bg-neutral-50 rounded-xl p-2.5 border border-neutral-100", children: [_jsx("span", { className: "text-[10px] font-bold uppercase tracking-wider text-neutral-400 block", children: "Weekly Volume" }), _jsx("span", { className: "text-xs font-bold text-[#FF5500] mt-0.5 block font-mono", children: formatDistance(plan.weeklyTargetKm, unitSystem, true) })] })] }), _jsxs("div", { className: "space-y-1.5 pt-1", children: [_jsx("span", { className: "text-[10px] font-bold uppercase tracking-wider text-neutral-400 block", children: "Key Sessions This Week" }), _jsx("div", { className: "space-y-1", children: runningWorkouts.map((w) => {
                            const dateStr = w.date
                                ? formatWorkoutDate(w.date)
                                : (typeof w.dayOfWeek === 'number' ? formatWorkoutDate(getDateForDayOfWeek(w.dayOfWeek)) : '');
                            return (_jsxs("div", { className: "flex items-center justify-between text-xs py-1.5 px-2.5 bg-neutral-50/70 rounded-lg border border-neutral-100/80", children: [_jsxs("div", { className: "flex items-center space-x-1.5 min-w-0 pr-2", children: [_jsx("span", { className: "font-bold text-neutral-900 shrink-0 text-[11px]", children: w.dayName }), dateStr && (_jsxs(_Fragment, { children: [_jsx("span", { className: "text-neutral-300 text-[10px]", children: "\u00B7" }), _jsx("span", { className: "text-neutral-500 font-semibold text-[10px] shrink-0", children: dateStr })] })), _jsx("span", { className: "text-neutral-300 text-[10px]", children: "\u00B7" }), _jsx("span", { className: "text-neutral-600 truncate text-[11px]", children: w.title })] }), _jsx("span", { className: "font-mono font-bold text-[#FF5500] text-[11px] shrink-0", children: formatDistance(w.distanceKm, unitSystem, true) })] }, w.id || w.dayName));
                        }) })] }), plan.aiAdvice && (_jsxs("div", { className: "p-2.5 rounded-xl bg-orange-50/60 border border-orange-100 text-xs text-neutral-700 space-y-1", children: [_jsxs("div", { className: "flex items-center space-x-1.5 text-[#FF5500] font-bold text-[11px]", children: [_jsx(Sparkles, { className: "w-3.5 h-3.5" }), _jsx("span", { children: "Coach Note" })] }), _jsx("p", { className: "text-[11px] leading-relaxed text-neutral-600", children: plan.aiAdvice })] })), _jsxs("div", { className: "pt-2 flex items-center space-x-2", children: [!isActive ? (_jsx(Button, { variant: "primary", size: "sm", onClick: () => onApplyPlan?.(plan), leftIcon: _jsx(Check, { className: "w-3.5 h-3.5" }), className: "flex-1 font-bold text-xs shadow-glow-orange", children: "Apply to My Schedule" })) : (_jsxs("div", { className: "flex-1 text-center py-1.5 text-xs font-bold text-emerald-600 bg-emerald-50 rounded-xl flex items-center justify-center gap-1.5", children: [_jsx(Check, { className: "w-4 h-4" }), "Currently Active"] })), onViewDetails && (_jsx(Button, { variant: "secondary", size: "sm", onClick: () => onViewDetails(plan), className: "text-xs font-semibold", children: "Details" }))] })] }));
};
